### PR TITLE
Dev vs. Stable version

### PR DESCRIPTION
**Pull request by kkiesling**
This should address issue #18 for the docker builds. Two knew files have been added that are indicated with "-stable" which will check out the most recent tagged version of PyNE and build instead of the develop branch.

### CODE REVIEW

**Comment by scopatz** [comment]
For what it is worth, 16.04-dev fails because of bugs on develop. 

Also, perhaps more seriously, 17.04-stable fails because of bugs on master.  

I am fine with merging, this though. Thanks for putting this in @kkiesling!

**Comment by gonuke** [comment]
I think the u17.04-stable fails, for known reasons.  How should we handle this?

**Comment by scopatz** [comment]
Yeah, the u170.04-stable fails are because of actual breaks on the last release version. I think the fix is a new release.

**Comment by scopatz** [comment]
Which is why I don't think that those failures should block merging this :)

**Comment by gonuke** [comment]
I agree that the current state of the ecosystem means that these failures shouldn't block this merge, but...  These scripts become much less useful if they don't work.  A main purpose of this repo is to provide working scripts to navigate a relatively challenging build environment.

**Comment by kkiesling** [comment]
I do have the current issue of not being able to build the 17.04 version at all with these docker files. The "stable" version hangs up on a test and never finishes. The "dev" version gets errors in the test. When I added a process timeout to the stable version nosetests, I end up with the same error.

I guess my intention with this PR was to just update the 16.04 versions originally with the stable/dev option. And since there was also the 17.04 docker version, I would also add in that capability while I was at it.

**Comment by kkiesling** [comment]
Note - I just added a commit that better explains the dev vs stable option to the README (also includes just information that was not there before..).

**Comment by scopatz** [comment]
Thanks @kkiesling! I am going to merge these because they are needed :)

**Pull request merged**
