### PR TITLE
0.5.10 - updated stable version install script to be compatible w/ latest tagged version

### PR DESCRIPTION
**Pull request by kkiesling**
Added setuptools to the apt-get list and specified python2 or python3 for tests regardless of stable or dev.

It also looks like my editor stripped a bunch of trailing whitespaces as well on several lines. Lines of interest in each file:
- ubuntu_16.04-stable.dockerfile: lines 13-14, 71
- ubuntu_16.04.sh: lines 18-19
- ubuntu_mint.sh: function test_pyne

### CODE REVIEW

**Comment by gonuke** [comment]
Do you recall why we separated this out originally?

**Comment by kkiesling** [comment]
At one point the latest develop branch did not work on Ubuntu 16.04 so it was necessary to use the latest tagged version. That has since changed as there was a new tag 0.5.10 in early December and now the "stable" version includes changes to fix these errors. I think it is still a good idea to keep the option for "stable" or "dev" even if both currently work.

**Comment by scopatz** [comment]
Any reason not to merge this?

**Comment by kkiesling** [comment]
No - I would appreciate this being merged if you don't see anything wrong with it.

**Comment by scopatz** [comment]
Sorry for the delay!

**Pull request merged**
