### PR TITLE
Ubuntu 16 script and testing update

### PR DESCRIPTION
**Pull request by gonuke**
Adds support for Ubuntu 16.04 and changes recommended testing method for Ubuntu 15.04 to CI-based method (see pyne/pyne#880)

### CODE REVIEW

**Comment by kkiesling** [comment]
Looks good to me.

**Comment by katyhuff** [comment]
Did this close #880 ?

**Comment by gonuke** [comment]
Yes it did close #880

**Comment by gonuke** [comment]
On 2nd thoughts... this changed the behavior in the automated install scripts to match what works, but I think pyne/pyne#880 should be a documentation change??

**Pull request merged**
